export * from './Header'
export * from './Hero'
export * from './About'
export * from './Tape'
export * from './Projects'
export * from './Testimonials'
export * from './FAQs'
export * from './Footer'
